# Manually created as-at 2021-12-01
# Last updated as-at 2022-12-08
# Lower-pinned packages to 2- or 3-level version >= a.b.*
# REIMINDER: these packages are not picked up by packing into dist, so must be
# separately installed in the conda env that calls this dist
name: oreum_core
dependencies:
- mkl==2021.4.*  # NOTE 2022 version(s) dont work on MacOS https://stackoverflow.com/a/71640311/1165112
- mkl-service==2.4.*
- pip>=22.1.*
- python==3.9.*
- conda-forge::blas=*[build=*mkl]  # force mamba install MKL
- conda-forge::pymc3==3.11.4         # install here to compile w/ Intel MKL BLAS
- conda-forge::theano-pymc==1.1.2    # install here to compile w/ Intel MKL BLAS
- pip:
  - pip-licenses>=3.5.*
  - pre-commit>=2.20.*
