# Manually created as-at 2021-12-01
# Last updated as-at 2023-03-29
# NOTE:
#  + Creates a conda env for local development
#  + Install with mamba via Makefile, force MKL via "libblas" (note not "blas")
#  + Assume running on Intel x86 AMD64 processors
name: oreum_core
dependencies:
- mkl==2021.4.*  # NOTE 2022 version(s) dont work on MacOS https://stackoverflow.com/a/71640311/1165112
- mkl-service==2.4.*
- numpy==1.23.*                         # force compile w/ Intel MKL BLAS
- python==3.10.*
- conda-forge::libblas=*[build=*mkl]    # force mamba install MKL
- conda-forge::libcblas=*[build=*mkl]   # force mamba install MKL
- conda-forge::liblapack=*[build=*mkl]  # force mamba install MKL
# - conda-forge::pymc>=5.2.0              # force compile w/ Intel MKL BLAS
