# Manually created as-at 2021-12-01
# Last updated as-at 2025-01-24
# NOTES:
#  + Creates a virtual env for project development
#  + Require running on Apple Silicon ARM64 (NOT Intel x86 AMD64 CPU via Rosetta2)
#  + Install with mamba via Makefile, there's also a fuller set of deps to be
#    installed by pip in the pyproject.toml
#  + numpy not strictly needed here because it's brought in by pymc but because
#    we're explcit about BLAS/LAPACK from acccelerate, then also numpy.
#    also see https://numpy.org/install/ and https://github.com/numpy/numpy/pull/24053
#  + libblas, libcblas, liblapack, not strictly needed here but we want to be
#    explicit about forcing BLAS to use Accelerate
name: oreum_core
channels:
  - conda-forge
  # - defaults
dependencies:
- conda-forge::ipykernel>=6.29.0
- conda-forge::numpy>=1.26.0  # see NOTES
- conda-forge::libblas=*[build=*accelerate]  # see NOTES
- conda-forge::libcblas=*[build=*accelerate]  # see NOTES
- conda-forge::liblapack=*[build=*accelerate]  # see NOTES
- conda-forge::python==3.12.*
