name: oreum_core
channels:
- defaults
dependencies:
- mkl==2021.4.*
- mkl-service==2.4.*
- numpy==1.21.*      # install here to compile against Intel MKL BLAS
- pip==21.2.*
- python==3.9.*
- conda-forge::pymc3==3.11.4 # install here to compile against Intel MKL BLAS
- conda-forge::theano-pymc==1.1.2 # install here to compile against Intel MKL BLAS
