# Manually created as-at 2021-12-01
# Last updated as-at 2023-10-04
# NOTE:
#  + Creates a virtual env for project usage
#  + Require running on Intel x86 AMD64 CPU (or Rosetta2 on MacOS)
#  + Install with mamba via Makefile, there's also a fuller set of deps to be
#    installed by pip in the pyproject.toml
#  + Force MKL version: 2022 version(s) dont work on MacOS
#    see https://stackoverflow.com/a/71640311/1165112
#  + Force install BLAS with MKL via libblas (note not "blas")
#  + Force install numpy MKL: only available in defaults (pkgs/main)
#    see https://github.com/conda-forge/numpy-feedstock/issues/84#issuecomment-385186685
name: oreum_core
channels:
  - conda-forge
  # - defaults
dependencies:
- pkgs/main::numpy==1.24.3  # force numpy MKL see NOTE
- conda-forge::ipykernel>=6.23.1
- conda-forge::libblas=*[build=*mkl]  # force BLAS with MKL see NOTE
- conda-forge::libcblas=*[build=*mkl]  # force BLAS with MKL see NOTE
- conda-forge::liblapack=*[build=*mkl]  # force BLAS with MKL see NOTE
- conda-forge::mkl==2021.4.*  # force MKL version see NOTE
- conda-forge::mkl-service==2.4.*
- conda-forge::python==3.11.*
- conda-forge::pymc>=5.9.0
