name: black
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: '-v -S -C -t py39 --check --diff --color --extend-exclude = """*./__pycache__/"""'
          src: './oreum_core'
          version: '22.3.*'
