name: interrogate
on: [pull_request]
jobs:
  interrogate-docstring-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install interrogate
        run: "pip install interrogate>=1.5.*"
      - name: run interrogate
        run: "interrogate -v -I -f0.8 -g oreum_core/"
