name: publish_to_testpypi
on:
  pull_request:
    types:
      - ready_for_review
    # branches:
    #   - master

jobs:
  publish_to_testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Build package
        run: make build
      - name: Publish to TestPyPI
        run: FLIT_PASSWORD=${{ secrets.TESTPYPI_TOKEN_OREUM_CORE_GITHUB }} make publish_to_testpypi

# NOTE
# This will execute when a draft PR (that targets master) is marked ready for review,
# using the contents of the inbound branch at that point
# https://stackoverflow.com/questions/62331829/how-to-get-the-target-branch-of-the-github-pull-request-from-an-actions
