name: automatic rebase deps
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  rebase:
    name: Rebase `deps` with `master`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: deps
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/master
          git push origin deps --force
